"""End-to-End Triple-Provider Acceptance driver.

Runs the complete platform flow (idea -> FS -> analysis -> refine -> tasks ->
impact -> collab -> build -> exports) three times (once per provider), then
runs the reverse-FS pipeline three times against the first project's build
artifacts, then exercises every remaining MCP surface and writes a
report to ``reports/e2e-final.md``.

Each phase is idempotent and persisted to ``.e2e_runtime.json`` so reruns
pick up where they left off. Failures are captured into runtime.repairs
and retried via the repair loop.

Usage::

    python -m scripts.e2e_full              # run every enabled phase
    python -m scripts.e2e_full --phases=preflight,project_api
    python -m scripts.e2e_full --reset       # wipe runtime first
"""

from __future__ import annotations

import argparse
import asyncio
import io
import json
import sys
import time
import zipfile
from pathlib import Path

import httpx

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts._e2e_utils import (  # noqa: E402
    BACKEND_URL,
    REPORT_DIR,
    BackendClient,
    ProjectState,
    ReverseRun,
    Runtime,
    banner,
    logger,
    repair_loop,
    run_analysis_with_progress,
    setup_logging,
    step,
    switch_provider,
    wait_for_quality,
)
from scripts.e2e_scenario import (  # noqa: E402
    COMPLEXITY,
    EXPECTED,
    GUIDED_ANSWERS,
    IDEA_TEXT,
    INDUSTRY,
    PROJECT_SMOKE_ONLY,
    PROJECTS,
)

# ── Static TODO code (keeps the build leg token-free) ─────────────────

STATIC_TODO_SOURCES = {
    "main.py": (
        "from __future__ import annotations\n"
        "from fastapi import FastAPI, HTTPException\n"
        "from pydantic import BaseModel\n\n"
        "app = FastAPI()\n"
        "TODOS: list[dict] = []\n"
        "_NEXT_ID = 1\n\n"
        "class TodoIn(BaseModel):\n"
        "    text: str\n\n"
        "@app.get('/health')\n"
        "def health() -> dict:\n"
        "    return {'status': 'ok'}\n\n"
        "@app.get('/todos')\n"
        "def list_todos() -> list[dict]:\n"
        "    return list(TODOS)\n\n"
        "@app.post('/todos')\n"
        "def create_todo(body: TodoIn) -> dict:\n"
        "    global _NEXT_ID\n"
        "    entry = {'id': _NEXT_ID, 'text': body.text}\n"
        "    TODOS.append(entry)\n"
        "    _NEXT_ID += 1\n"
        "    return entry\n\n"
        "@app.delete('/todos/{todo_id}')\n"
        "def delete_todo(todo_id: int) -> dict:\n"
        "    for i, t in enumerate(TODOS):\n"
        "        if t['id'] == todo_id:\n"
        "            TODOS.pop(i)\n"
        "            return {'deleted': todo_id}\n"
        "    raise HTTPException(status_code=404, detail='not found')\n"
    ),
    "test_main.py": (
        "from fastapi.testclient import TestClient\n"
        "from main import app, TODOS\n\n"
        "client = TestClient(app)\n\n"
        "def setup_function() -> None:\n"
        "    TODOS.clear()\n\n"
        "def test_health() -> None:\n"
        "    assert client.get('/health').json() == {'status': 'ok'}\n\n"
        "def test_crud_flow() -> None:\n"
        "    assert client.get('/todos').json() == []\n"
        "    created = client.post('/todos', json={'text': 'buy milk'}).json()\n"
        "    assert created['text'] == 'buy milk' and created['id'] == 1\n"
        "    assert len(client.get('/todos').json()) == 1\n"
        "    assert client.delete(f\"/todos/{created['id']}\").status_code == 200\n"
        "    assert client.delete('/todos/999').status_code == 404\n"
    ),
    "requirements.txt": "fastapi==0.115.0\nuvicorn==0.30.6\npytest==8.3.3\nhttpx==0.27.0\n",
    "README.md": (
        "# Tiny TODO API\n\n"
        "Generated by the FS Intelligence Platform E2E acceptance run.\n"
        "Run with ``uvicorn main:app`` and test with ``pytest``.\n"
    ),
}

STATIC_FILE_TYPE = {
    "main.py": "source",
    "test_main.py": "test",
    "requirements.txt": "config",
    "README.md": "docs",
}


# ── Phase implementations ─────────────────────────────────────────────


class Driver:
    def __init__(self, runtime: Runtime) -> None:
        self.rt = runtime

    async def preflight(self, client: BackendClient) -> None:
        data = await client.jget("/health")
        assert data["data"]["status"] == "healthy", data
        providers = (await client.jget("/api/orchestration/providers"))["data"]
        names = {p["name"] for p in providers}
        for required in ("api", "claude_code", "cursor"):
            assert required in names, f"Provider {required} missing"
            p = next(x for x in providers if x["name"] == required)
            logger.info("  provider %-12s  healthy=%s", required, p.get("healthy"))
        await client.jget("/api/orchestration/capabilities")
        await client.jget("/api/orchestration/mcp-config")

    async def _create_project(self, client: BackendClient, spec: dict) -> ProjectState:
        state = self.rt.projects.get(spec["key"]) or ProjectState(
            provider=spec["provider"],
            name=spec["name"],
        )
        self.rt.projects[spec["key"]] = state

        if state.project_id:
            logger.info("  project already exists: %s", state.project_id)
            return state

        try:
            created = await client.jpost(
                "/api/projects",
                json={"name": spec["name"], "description": spec["description"]},
            )
            state.project_id = created["data"]["id"]
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code == 409:
                listing = await client.jget("/api/projects")
                for p in listing["data"]["projects"]:
                    if p["name"] == spec["name"]:
                        state.project_id = p["id"]
                        break
            else:
                raise
        self.rt.save()
        return state

    async def _generate_idea(self, client: BackendClient, spec: dict, state: ProjectState) -> None:
        if state.document_id:
            logger.info("  idea already generated: doc=%s", state.document_id)
            return
        if spec["idea_mode"] == "quick":
            resp = await client.jpost(
                "/api/idea/generate",
                json={"idea": IDEA_TEXT, "industry": INDUSTRY, "complexity": COMPLEXITY},
            )
            state.document_id = resp["data"]["document_id"]
            state.filename = resp["data"]["filename"]
            state.section_count = resp["data"]["section_count"]
        else:
            # guided mode: step 0 gets questions, step 1 generates FS with canned answers
            q = await client.jpost(
                "/api/idea/guided",
                json={"idea": IDEA_TEXT, "step": 0, "industry": INDUSTRY, "complexity": COMPLEXITY},
            )
            session_id = q["data"]["session_id"]
            resp = await client.jpost(
                "/api/idea/guided",
                json={"session_id": session_id, "step": 1, "answers": GUIDED_ANSWERS},
            )
            state.document_id = resp["data"]["document_id"]
            state.filename = resp["data"]["filename"]
            state.section_count = resp["data"]["section_count"]
        logger.info(
            "  generated FS doc=%s filename=%s sections=%s",
            state.document_id,
            state.filename,
            state.section_count,
        )
        # Assign to project
        if state.project_id:
            try:
                await client.jpost(
                    f"/api/projects/{state.project_id}/documents/{state.document_id}",
                )
            except httpx.HTTPStatusError as exc:
                logger.warning("  project-assign failed (non-fatal): %s", exc)
        self.rt.save()

    async def _analyze_document(self, client: BackendClient, state: ProjectState) -> None:
        doc = await client.jget(f"/api/fs/{state.document_id}")
        if str(doc["data"]["status"]).lower() == "complete":
            logger.info("  analysis already complete")
        else:
            logger.info("  running analysis (claude/cursor providers can take 10-25min)...")
            await run_analysis_with_progress(client, state.document_id)
            logger.info("  analysis done")

        quality = await wait_for_quality(
            client,
            state.document_id,
            min_score=EXPECTED["min_quality"],
            max_refine=EXPECTED["max_refine_attempts"],
        )
        state.quality_score = float(quality["quality_score"]["overall"])
        tasks = await client.jget(f"/api/fs/{state.document_id}/tasks")
        state.task_count = len(tasks["data"]["tasks"])
        amb = await client.jget(f"/api/fs/{state.document_id}/ambiguities")
        state.high_ambiguities = sum(1 for a in amb["data"] if (a.get("severity") or "").lower() == "high")
        # exercise the side endpoints
        await client.jget(f"/api/fs/{state.document_id}/contradictions")
        await client.jget(f"/api/fs/{state.document_id}/edge-cases")
        await client.jget(f"/api/fs/{state.document_id}/tasks/dependency-graph")
        await client.jget(f"/api/fs/{state.document_id}/traceability")
        logger.info(
            "  quality=%.1f tasks=%d high_amb=%d",
            state.quality_score,
            state.task_count,
            state.high_ambiguities,
        )
        self.rt.save()

    async def _collab_and_approval(self, client: BackendClient, state: ProjectState) -> None:
        comment = await client.jpost(
            f"/api/fs/{state.document_id}/sections/0/comments",
            json={"text": "E2E ack - looks good @reviewer", "user_id": "e2e_bot"},
        )
        cid = comment["data"]["id"]
        await client.jget(f"/api/fs/{state.document_id}/comments")
        await client.jpatch(f"/api/fs/{state.document_id}/comments/{cid}/resolve")
        try:
            await client.jpost(
                f"/api/fs/{state.document_id}/submit-for-approval",
                json={"approver_id": "e2e_reviewer"},
            )
            await client.jpost(
                f"/api/fs/{state.document_id}/approve",
                json={"approver_id": "e2e_reviewer", "comment": "E2E auto-approve"},
            )
        except httpx.HTTPStatusError as exc:
            logger.warning("  approval flow non-fatal: %s", exc)
        await client.jget(f"/api/fs/{state.document_id}/approval-status")

    async def _build_and_register(self, client: BackendClient, state: ProjectState) -> None:
        await client.jpost(f"/api/fs/{state.document_id}/build-state")
        await client.jpatch(
            f"/api/fs/{state.document_id}/build-state",
            json={"status": "RUNNING", "stack": "Python + FastAPI", "output_folder": "./output"},
        )
        prompt = await client.jget(f"/api/fs/{state.document_id}/build-prompt")
        logger.info(
            "  build prompt chars=%d", len(prompt.get("prompt", prompt.get("data", {}).get("prompt", "") or ""))
        )

        await client.jget(f"/api/fs/{state.document_id}/pre-build-check")

        # Register each static file against every task so verify_task_completion passes
        tasks_resp = await client.jget(f"/api/fs/{state.document_id}/tasks")
        tasks = tasks_resp["data"]["tasks"]
        if not tasks:
            logger.warning("  no tasks — skipping file registry")
            return
        first_task = tasks[0]["task_id"]
        for fname, _ in STATIC_TODO_SOURCES.items():
            await client.jpost(
                f"/api/fs/{state.document_id}/file-registry",
                json={
                    "task_id": first_task,
                    "section_id": "0",
                    "file_path": f"./output/{fname}",
                    "file_type": STATIC_FILE_TYPE[fname],
                },
            )
        # Verify + mark every task COMPLETE (all point at the same registered files)
        for t in tasks:
            tid = t["task_id"]
            # re-register files against this specific task so verify passes
            if tid != first_task:
                await client.jpost(
                    f"/api/fs/{state.document_id}/file-registry",
                    json={
                        "task_id": tid,
                        "section_id": str(t.get("section_index", 0)),
                        "file_path": "./output/main.py",
                        "file_type": "source",
                    },
                )
                await client.jpost(
                    f"/api/fs/{state.document_id}/file-registry",
                    json={
                        "task_id": tid,
                        "section_id": str(t.get("section_index", 0)),
                        "file_path": "./output/test_main.py",
                        "file_type": "test",
                    },
                )
            try:
                await client.jget(f"/api/fs/{state.document_id}/tasks/{tid}/context")
                await client.jget(f"/api/fs/{state.document_id}/tasks/{tid}/verify")
                await client.jpatch(
                    f"/api/fs/{state.document_id}/tasks/{tid}",
                    json={"status": "COMPLETE"},
                )
            except httpx.HTTPStatusError as exc:
                logger.warning("  task %s verify/complete non-fatal: %s", tid, exc)

        await client.jpatch(
            f"/api/fs/{state.document_id}/build-state",
            json={"status": "COMPLETE"},
        )
        reg = await client.jget(f"/api/fs/{state.document_id}/file-registry")
        logger.info("  registered files: %d", reg["data"]["total"])
        await client.jget(f"/api/fs/{state.document_id}/post-build-check")
        # Snapshot
        snap = await client.jpost(
            f"/api/fs/{state.document_id}/snapshots",
            json={"label": f"E2E snapshot ({state.provider})"},
        )
        logger.info("  snapshot created: %s", snap.get("data", {}).get("id"))
        state.build_state_status = "COMPLETE"
        self.rt.save()

    async def _exports(self, client: BackendClient, state: ProjectState) -> None:
        try:
            await client.jget(f"/api/fs/{state.document_id}/test-cases")
        except httpx.HTTPStatusError as exc:
            logger.warning("  test-cases non-fatal: %s", exc)

        for path in (
            f"/api/fs/{state.document_id}/export/pdf",
            f"/api/fs/{state.document_id}/export/docx",
        ):
            try:
                await client.jget(path)
            except httpx.HTTPStatusError as exc:
                logger.warning("  export %s non-fatal: %s", path, exc)

        for path in (
            f"/api/fs/{state.document_id}/export/jira",
            f"/api/fs/{state.document_id}/export/confluence",
        ):
            try:
                await client.jpost(path, json={"dry_run": True})
            except httpx.HTTPStatusError as exc:
                logger.warning("  export %s non-fatal (likely missing creds): %s", path, exc)

    async def run_project(self, client: BackendClient, spec: dict) -> ProjectState:
        logger.info(banner(f"PROJECT {spec['key'].upper()} — provider={spec['provider']}"))
        await switch_provider(client, spec["provider"])
        state = await self._create_project(client, spec)
        await repair_loop(
            f"idea:{spec['key']}",
            lambda: self._generate_idea(client, spec, state),
            self.rt,
            max_attempts=3,
            backoff=5.0,
        )
        if spec["provider"] in PROJECT_SMOKE_ONLY:
            # Smoke-only: kick analyze, confirm provider started producing output,
            # then cancel. Skips heavy collab/build/exports that would waste tokens.
            await repair_loop(
                f"smoke:{spec['key']}",
                lambda: self._smoke_analyze(client, state, spec),
                self.rt,
                max_attempts=1,
                backoff=5.0,
            )
            state.notes.append(
                f"smoke-only run for provider={spec['provider']}: analyze started & cancelled to save tokens"
            )
            state.build_state_status = "SKIPPED_SMOKE"
            self.rt.save()
            return state

        await repair_loop(
            f"analyze:{spec['key']}",
            lambda: self._analyze_document(client, state),
            self.rt,
            max_attempts=2,
            backoff=10.0,
        )
        await repair_loop(
            f"collab:{spec['key']}",
            lambda: self._collab_and_approval(client, state),
            self.rt,
            max_attempts=3,
            backoff=3.0,
        )
        await repair_loop(
            f"build:{spec['key']}",
            lambda: self._build_and_register(client, state),
            self.rt,
            max_attempts=3,
            backoff=3.0,
        )
        await repair_loop(
            f"exports:{spec['key']}",
            lambda: self._exports(client, state),
            self.rt,
            max_attempts=2,
            backoff=3.0,
        )
        return state

    async def _smoke_analyze(
        self,
        client: BackendClient,
        state: ProjectState,
        spec: dict,
    ) -> None:
        """Confirm provider actually starts the pipeline, then cancel.

        Token-minimal: we fire POST /analyze in the background, poll
        analysis-progress until at least one node is executing (the LLM
        round-trip has actually begun under the selected provider), then
        cancel and assert the cancel took effect.

        Cursor provider is a special case: the backend refuses server-side
        LLM calls (HTTP 409) to protect the user's API credits — token
        work runs inside the Cursor IDE. We treat the 409 as PASS.
        """
        # Cursor: server-side analyze must be refused (409). That refusal
        # is itself the correctness proof — no tokens hit OpenRouter.
        if spec["provider"] == "cursor":
            r = await client.request(
                "POST",
                f"/api/fs/{state.document_id}/analyze",
                timeout=20.0,
            )
            if r.status_code == 409:
                logger.info(
                    "  [smoke] cursor provider correctly refused server-side analyze "
                    "(HTTP 409). Token-safe. Use Phase 6 Cursor IDE kickoff for a real run."
                )
                state.notes.append("smoke OK: cursor provider refused server-side LLM (HTTP 409) — tokens protected")
                return
            raise AssertionError(
                f"cursor provider did NOT refuse analyze (status={r.status_code}) — "
                f"this would have consumed OpenRouter credits! body={r.text[:500]!r}"
            )

        # If already complete from prior run, nothing to do.
        doc = await client.jget(f"/api/fs/{state.document_id}")
        status = str(doc["data"]["status"]).upper()
        if status == "COMPLETE":
            logger.info("  [smoke] document already COMPLETE — provider verified earlier")
            state.notes.append("smoke skipped: document already COMPLETE")
            return

        logger.info("  [smoke] kicking off analyze under provider=%s (will cancel)", spec["provider"])
        analyze_task = asyncio.create_task(client.request("POST", f"/api/fs/{state.document_id}/analyze"))

        started = False
        deadline = time.time() + 180.0  # 3 min budget to see the first LLM node run
        seen_nodes: set[str] = set()
        while time.time() < deadline:
            if analyze_task.done():
                break
            try:
                prog = await client.jget(f"/api/fs/{state.document_id}/analysis-progress")
                p = prog.get("data", {}) if isinstance(prog, dict) else {}
                doc_status = str(p.get("status") or "").upper()
                current = p.get("current_node")
                completed = p.get("completed_nodes") or []
                if current:
                    seen_nodes.add(current)
                if current or completed:
                    started = True
                    logger.info(
                        "  [smoke] provider=%s is alive: status=%s node=%s completed=%d",
                        spec["provider"],
                        doc_status,
                        current,
                        len(completed),
                    )
                    break
                if doc_status in ("COMPLETE", "ERROR"):
                    started = True
                    break
            except Exception as exc:  # noqa: BLE001
                logger.debug("smoke progress probe: %s", exc)
            await asyncio.sleep(5)

        # Whatever happened, issue cancel to unblock and stop token spend
        try:
            await client.jpost(f"/api/fs/{state.document_id}/cancel-analysis")
            logger.info("  [smoke] cancel-analysis sent")
        except Exception as exc:  # noqa: BLE001
            logger.warning("  [smoke] cancel-analysis call failed: %s", exc)

        # Give the pipeline a moment to observe the cancel signal, then hard-cancel
        try:
            await asyncio.wait_for(asyncio.shield(analyze_task), timeout=45.0)
        except (TimeoutError, asyncio.CancelledError):
            analyze_task.cancel()
            try:
                await analyze_task
            except (asyncio.CancelledError, Exception):  # noqa: BLE001
                pass
        except Exception as exc:  # noqa: BLE001
            # Likely backend returned a 409/500 due to cancel — acceptable in smoke mode
            logger.info("  [smoke] analyze task resolved with: %s", exc)

        if not started:
            raise AssertionError(f"provider={spec['provider']} did not produce any pipeline progress within 180s")
        state.notes.append(
            f"smoke OK: provider={spec['provider']} observed on nodes {sorted(seen_nodes) or ['(none logged)']}"
        )

    # ── Reverse FS ────────────────────────────────────────

    def _build_code_zip(self) -> bytes:
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for fname, content in STATIC_TODO_SOURCES.items():
                zf.writestr(f"todo_api/{fname}", content)
        return buf.getvalue()

    async def reverse_upload(self, client: BackendClient) -> str:
        if self.rt.code_upload_id:
            logger.info("  code upload already exists: %s", self.rt.code_upload_id)
            return self.rt.code_upload_id
        zip_bytes = self._build_code_zip()
        files = {"file": ("todo_api.zip", zip_bytes, "application/zip")}
        r = await client.request("POST", "/api/code/upload", files=files)
        r.raise_for_status()
        data = r.json()
        upload_id = data["data"]["upload_id"] if "upload_id" in data["data"] else data["data"]["id"]
        self.rt.code_upload_id = upload_id
        self.rt.save()
        logger.info("  uploaded code: %s", upload_id)
        return upload_id

    async def reverse_generate(self, client: BackendClient, provider: str) -> ReverseRun:
        run = self.rt.reverses.get(provider) or ReverseRun(provider=provider)
        self.rt.reverses[provider] = run
        if run.document_id:
            logger.info("  reverse-FS already generated for %s: %s", provider, run.document_id)
            return run
        await switch_provider(client, provider)

        smoke = provider in PROJECT_SMOKE_ONLY
        if smoke and provider == "cursor":
            # Cursor: expect 409 refusal (no server-side tokens).
            r = await client.request(
                "POST",
                f"/api/code/{self.rt.code_upload_id}/generate-fs",
                timeout=20.0,
            )
            if r.status_code == 409:
                logger.info("  [smoke] reverse-FS cursor correctly refused (HTTP 409) — tokens protected")
                run.notes.append("reverse-FS smoke OK: cursor refused server-side (HTTP 409)")
                self.rt.save()
                return run
            raise AssertionError(f"reverse-FS cursor did NOT refuse (status={r.status_code}) body={r.text[:400]!r}")

        if smoke:
            # Token-saving smoke: verify the reverse pipeline actually starts
            # (code upload transitions to GENERATING), then bail out early.
            logger.info("  [smoke] reverse-FS kickoff for provider=%s (will abort after status transition)", provider)
            gen_task = asyncio.create_task(
                client.request(
                    "POST",
                    f"/api/code/{self.rt.code_upload_id}/generate-fs",
                    timeout=httpx.Timeout(connect=10, read=900, write=60, pool=10),
                )
            )
            started = False
            deadline = time.time() + 120.0
            while time.time() < deadline and not gen_task.done():
                try:
                    upl = await client.jget(f"/api/code/{self.rt.code_upload_id}")
                    s = str(upl.get("data", {}).get("status") or "").upper()
                    if s in ("GENERATING", "GENERATED", "ERROR"):
                        started = True
                        logger.info("  [smoke] reverse-FS provider=%s reached status=%s", provider, s)
                        break
                except Exception as exc:  # noqa: BLE001
                    logger.debug("reverse smoke poll: %s", exc)
                await asyncio.sleep(4)
            if not gen_task.done():
                gen_task.cancel()
            try:
                await gen_task
            except (asyncio.CancelledError, Exception):  # noqa: BLE001
                pass
            run.notes.append(
                f"reverse-FS smoke OK: provider={provider} transitioned into GENERATING (no full completion to save tokens)"
                if started
                else f"reverse-FS smoke INCONCLUSIVE: provider={provider} did not transition within 120s"
            )
            self.rt.save()
            if not started:
                raise AssertionError(f"reverse-FS {provider} did not transition within 120s")
            return run

        r = await client.request(
            "POST",
            f"/api/code/{self.rt.code_upload_id}/generate-fs",
            timeout=httpx.Timeout(connect=10, read=900, write=60, pool=10),
        )
        r.raise_for_status()
        data = r.json()
        doc = data["data"]
        run.document_id = doc.get("generated_fs_id") or doc.get("document_id") or doc.get("fs_id") or doc.get("id")
        run.section_count = len(doc.get("sections", []) or []) or doc.get("section_count")
        run.flow_count = doc.get("flow_count") or 0
        try:
            q = await client.jget(f"/api/fs/{run.document_id}/quality-score")
            run.quality_score = float(q["data"]["quality_score"]["overall"])
        except Exception as exc:
            logger.warning("  quality fetch failed for reverse %s: %s", provider, exc)
        self.rt.save()
        logger.info(
            "  reverse-FS %s: doc=%s sections=%s flows=%s quality=%s",
            provider,
            run.document_id,
            run.section_count,
            run.flow_count,
            run.quality_score,
        )
        return run

    # ── MCP tool matrix ──────────────────────────────────

    async def mcp_exercise(self, client: BackendClient) -> None:
        first = next(iter(self.rt.projects.values()), None)
        if not first or not first.document_id:
            logger.warning("  no primary project — skipping MCP matrix")
            return
        session = await client.jpost(
            "/api/mcp/sessions",
            json={"document_id": first.document_id, "client_type": "e2e_driver"},
        )
        sid = session["data"]["id"]
        self.rt.mcp_session_id = sid
        for ev in ("build_started", "task_in_progress", "task_complete", "build_complete"):
            await client.jpost(
                f"/api/mcp/sessions/{sid}/events",
                json={"event_type": ev, "payload": {"source": "e2e_bot"}},
            )
        events = await client.jget(f"/api/mcp/sessions/{sid}/events")
        logger.info("  mcp session %s: %d events", sid, len(events["data"]["events"]))

        doc_id = first.document_id
        for path in (
            "/api/library/search?q=todo",
            f"/api/fs/{doc_id}/duplicates",
            "/api/activity-log",
            f"/api/fs/{doc_id}/audit-log",
            "/api/projects",
            "/api/idea/health",
            "/api/orchestration/providers",
        ):
            try:
                await client.jget(path)
                logger.info("  MCP/tool path OK: %s", path)
            except httpx.HTTPStatusError as exc:
                logger.warning("  misc %s non-fatal: %s", path, exc)
        self.rt.save()

    # ── Cursor IDE kickoff (Phase 6) ─────────────────────

    async def cursor_ide_kickoff(self, client: BackendClient) -> None:
        """Emit the copy/paste prompt for a real Cursor IDE run and open an
        MCP monitoring session. This is the 'hybrid' acceptance step — the
        human runs the build inside Cursor while the driver tails events.
        """
        cursor_proj = self.rt.projects.get("cursor")
        if not cursor_proj or not cursor_proj.document_id:
            logger.warning("  no cursor project — skipping IDE kickoff")
            return

        mcp_cfg = await client.jget("/api/orchestration/mcp-config")
        cursor_snippet = (mcp_cfg.get("data") or {}).get("cursor", {})
        prompt_template = cursor_snippet.get(
            "agent_prompt",
            "Use the start_build_loop prompt for document <document_id>.",
        )
        prompt = prompt_template.replace("<document_id>", cursor_proj.document_id)
        config_path = cursor_snippet.get("path", ".cursor/mcp.json")
        snippet_json = json.dumps(cursor_snippet.get("snippet", {}), indent=2)

        session = await client.jpost(
            "/api/mcp/sessions",
            json={
                "document_id": cursor_proj.document_id,
                "client_type": "cursor_ide_human",
            },
        )
        sid = session["data"]["id"]
        self.rt.mcp_session_id = sid
        self.rt.save()

        kickoff_path = REPORT_DIR / "cursor_ide_kickoff.md"
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        with kickoff_path.open("w", encoding="utf-8") as fh:
            fh.write("# Cursor IDE — Manual Acceptance Kickoff\n\n")
            fh.write(f"Document: `{cursor_proj.document_id}`\n\n")
            fh.write(f"MCP session: `{sid}`\n\n")
            fh.write("## 1. MCP config\n\n")
            fh.write(f"Place this JSON at `{config_path}`:\n\n")
            fh.write("```json\n" + snippet_json + "\n```\n\n")
            fh.write("## 2. Agent prompt\n\n")
            fh.write("Paste into Cursor Agent Mode:\n\n")
            fh.write("```\n" + prompt + "\n```\n\n")
            fh.write("## 3. Monitoring\n\n")
            fh.write(
                "The driver is polling "
                f"`/api/mcp/sessions/{sid}/events` every 10s. When the "
                "build completes in Cursor, run `e2e_full --phases=cursor_verify` "
                "to assert file_registry + post-build-check.\n"
            )

        logger.info("  cursor-ide kickoff instructions: %s", kickoff_path)
        logger.info("  cursor-ide MCP session: %s", sid)
        logger.info("  paste the following in Cursor Agent Mode:")
        logger.info("    %s", prompt)

    async def cursor_ide_verify(self, client: BackendClient) -> None:
        """Post-Cursor-IDE-run verification: file_registry + post-build-check."""
        cursor_proj = self.rt.projects.get("cursor")
        if not cursor_proj or not cursor_proj.document_id:
            raise RuntimeError("no cursor project to verify")
        doc_id = cursor_proj.document_id

        registry = await client.jget(f"/api/fs/{doc_id}/file-registry")
        files = registry.get("data", {}).get("files", []) or []
        post_check = await client.jget(f"/api/fs/{doc_id}/post-build-check")
        post_data = post_check.get("data", {}) or {}

        cursor_proj.notes.append(
            f"cursor-ide verify: file_registry={len(files)} files, "
            f"post-build-check={post_data.get('passed', post_data)}"
        )
        self.rt.save()
        logger.info(
            "  cursor-ide verify: registry=%d files, post-build-check=%s",
            len(files),
            post_data.get("passed", post_data),
        )
        if len(files) == 0:
            logger.warning("  [warn] file_registry empty -- Cursor IDE run may not have started / completed")

    # ── Report ────────────────────────────────────────────

    def write_report(self) -> Path:
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        target = REPORT_DIR / "e2e-final.md"
        lines: list[str] = []
        lines.append("# E2E Triple-Provider Acceptance Report")
        lines.append("")
        lines.append(f"Generated at: {time.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"Backend: {BACKEND_URL}")
        lines.append("")
        lines.append("## Projects")
        lines.append("")
        lines.append("| Key | Provider | Project ID | Doc ID | Sections | Tasks | Quality | HighAmb | Build |")
        lines.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- |")
        for key, p in self.rt.projects.items():
            lines.append(
                f"| {key} | {p.provider} | `{p.project_id}` | `{p.document_id}` | "
                f"{p.section_count} | {p.task_count} | "
                f"{p.quality_score or 'n/a':>5} | {p.high_ambiguities} | {p.build_state_status} |"
            )
        lines.append("")
        lines.append("## Reverse FS Comparison")
        lines.append("")
        lines.append("| Provider | Doc ID | Sections | Flows | Quality |")
        lines.append("| --- | --- | --- | --- | --- |")
        for prov, r in self.rt.reverses.items():
            lines.append(
                f"| {prov} | `{r.document_id}` | {r.section_count} | {r.flow_count} | {r.quality_score or 'n/a'} |"
            )
        lines.append("")
        lines.append("## Phase status")
        lines.append("")
        for name, status in self.rt.phase_status.items():
            lines.append(f"- `{name}` -> **{status}**")
        lines.append("")
        lines.append("## Endpoint coverage")
        lines.append("")
        lines.append(f"Total endpoints hit: {len(self.rt.endpoint_hits)}")
        lines.append("")
        for key, n in sorted(self.rt.endpoint_hits.items()):
            lines.append(f"- `{key}` x {n}")
        lines.append("")
        if self.rt.repairs:
            lines.append("## Repair events")
            lines.append("")
            for rep in self.rt.repairs:
                lines.append(f"- `{rep['step']}` attempt={rep['attempt']} error=`{rep['error']}`")
            lines.append("")
        target.write_text("\n".join(lines), encoding="utf-8")
        logger.info("  wrote report: %s", target)
        return target


# ── Phase registry ────────────────────────────────────────────────────


async def main(phases: list[str] | None, reset_runtime: bool) -> int:
    setup_logging()
    if reset_runtime:
        from scripts._e2e_utils import RUNTIME_PATH

        RUNTIME_PATH.unlink(missing_ok=True)
    rt = Runtime.load()
    driver = Driver(rt)

    async with BackendClient(rt) as client:
        enabled = set(
            phases
            or [
                "preflight",
                "project_api",
                "project_claude",
                "project_cursor",
                "reverse",
                "mcp",
                "cursor_kickoff",
                "report",
            ]
        )

        if "preflight" in enabled:
            with step("preflight", rt):
                await driver.preflight(client)

        for spec in PROJECTS:
            phase = f"project_{spec['key']}"
            if phase not in enabled:
                continue
            with step(phase, rt):
                await driver.run_project(client, spec)

        if "reverse" in enabled:
            with step("reverse_upload", rt):
                await driver.reverse_upload(client)
            for prov in ("api", "claude_code", "cursor"):
                with step(f"reverse_{prov}", rt):
                    await driver.reverse_generate(client, prov)

        if "mcp" in enabled:
            with step("mcp_matrix", rt):
                await driver.mcp_exercise(client)

        if "cursor_kickoff" in enabled:
            with step("cursor_ide_kickoff", rt):
                await driver.cursor_ide_kickoff(client)

        if "cursor_verify" in enabled:
            with step("cursor_ide_verify", rt):
                await driver.cursor_ide_verify(client)

        if "report" in enabled:
            with step("report", rt):
                driver.write_report()

    logger.info(banner("E2E DRIVER COMPLETE"))
    fails = [k for k, v in rt.phase_status.items() if not v.startswith("ok")]
    if fails:
        logger.error("Failed phases: %s", ", ".join(fails))
        return 2
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--phases", default="", help="Comma-separated subset to run")
    parser.add_argument("--reset", action="store_true", help="Wipe runtime before starting")
    args = parser.parse_args()
    selected = [p.strip() for p in args.phases.split(",") if p.strip()]
    rc = asyncio.run(main(selected or None, args.reset))
    sys.exit(rc)
